version: "3.8"
services:
  todos:
    build: .
    volumes:
      - .:/todos
    ports:
      - 8001:8000
    image: app:fastapi
    container_name: todos_container
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db 
  pgadmin:
    container_name: pgadmin_todos
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres_todos
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db_todos
    ports:
      - 5432:5432


# http://localhost:5050/